<Project>
	<PropertyGroup>
		<VersionPrefix>0.0.1-preview-02</VersionPrefix>
		<VersionSuffix></VersionSuffix>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>Stef Heyenrath</Authors>
		<Company>AgentGuard.Extensions</Company>
		<Product>AgentGuard.Extensions</Product>
		<Copyright>Copyright (c) 2026 Stef Heyenrath</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/StefH/AgentGuard.Extensions</PackageProjectUrl>
		<RepositoryUrl>https://github.com/StefH/AgentGuard.Extensions</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>ai;agents;guardrails;safety;microsoft;pii;azure;dotnet;AgentGuard;extensions</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<!--<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
	</ItemGroup>
</Project>