<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Description>AgentGuard input text sanitizer.</Description>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsPackable)' != 'false'">
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AgentGuard" />
	</ItemGroup>
</Project>