<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<PackageId>AgentGuard.Extensions.Abstractions</PackageId>
		<RootNamespace>AgentGuard.Extensions.Abstractions</RootNamespace>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsPackable)' != 'false'">
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
</Project>